# Generated by Django 3.1.5 on 2021-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'Waitlist entries'},
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
    ]
