# Generated by Django 3.1.5 on 2021-01-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0002_auto_20210118_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Class Level'),
            preserve_default=False,
        ),
    ]
